# References:
#   https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-an-action-in-the-same-repository-as-the-workflow

name: Clean tmp
on: workflow_dispatch
jobs:
  clean_tmp:
    name: Clean tmp
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Clean tmp directory
        run: rm -rf *
        working-directory: ./tmp

      - name: Show tree
        run: tree