# Reference:
#   https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
#
# Summary:
#   This example triggers the workflow to run at 5:30 UTC every Monday-Thursday, 
#   but skips the Not on Monday or Wednesday step on Monday and Wednesday.

name: Cron Job Example 2
on:
  schedule:
    - cron: '30 5 * * 1,3'
    - cron: '30 5 * * 2,4'

jobs:
  test_schedule_2:
    name: Test Schedule 2
    runs-on: ubuntu-latest
    steps:
      - name: Not on Monday or Wednesday
        if: github.event.schedule != '30 5 * * 1,3'
        run: echo "This step will be skipped on Monday and Wednesday"
      - name: Every time
        run: echo "This step will always run"